name: Publish Docker image
run-name: ${{ github.event.pull_request.title }}
on:
  schedule:
    # At 02:00 AM, only on Tuesdays
    - cron: '0 2 * * 2'
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker-build-tag-push:
    name: Build and push Docker image to GitHub Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} >> .env
          echo DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} >> .env
          echo ASSISTANT_ID=${{ secrets.ASSISTANT_ID }} >> .env

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          provenance: false
          sbom: false
